# Generated by Django 5.0.1 on 2024-01-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='compeleted',
            new_name='completed',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to='images/'),
        ),
    ]
